version: 0.2

phases:
  install:
    commands:
      - echo Installing Project!!
      - pip install mkdocs
      - pip install mkdocs-material
  build:
    commands:
      - echo Building Project!!
      - mkdocs build
  post_build:
    commands:
      - echo PostBuilding Project!!
      - cd site && aws s3 sync s3://$BUCKET_NAME .
