site_name: AWS Cloud Developer Kit (CDK) Presentation
site_url: https://hasanaburayyan.github.io/aws-cdk-presentation/
site_description: A Deep Dive Into AWS CDK!
repo_url: https://github.com/hasanaburayyan/aws-cdk-presentation
nav:
  - 'index.md'
  - 'infrastructure-as-code/iac.md'
  - 'infrastructure-as-code/what-is-cdk.md'
  - 'cdk-key-concepts/cdk-key-concepts.md'
  - 'cdk-key-concepts/constructs.md'
  - 'creating-a-construct/testing-cdk.md'
  - 'building-reusable-code/building-reusable-code.md'
  - 'about/about-me.md'
theme: material
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - attr_list
